### ISSUE TITLE
Some Dockerfiles' parent images are deprecated

### ISSUE THREAD

**Issue by iamizaac** [eurocontrol-swim/SWIM-TI-YP-prototype#13]
Hello there, I am trying to make work this demo but i am facing some troubles
- I manage to correct some build errors due to some changes in debian packets URL, by updating the image parent of concerned Dockerfiles.
- I still have some SSL issues, the SWIM explorer does not work, I manage to manually create a subscribtion with CURL but not with the explorer.

Is it possible to contact you ? thanks for your help !

**Comment by iamizaac** [comment]
Last issue on "swim.sh provision" (I need to launch it twice, at first launch the database is not available : sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "postgres" (172.18.0.3), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
) 

Traceback (most recent call last):
  File "/app/provision/provision_broker.py", line 96, in <module>
    _add_users(config['BROKER_USERS'])
  File "/app/provision/provision_broker.py", line 69, in _add_users
    if client.user_exists(name):
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/app/lib/python3.11/site-packages/broker_rest_client/rabbitmq_rest_client.py", line 249, in user_exists
    self.get_user(name)
  File "/opt/conda/envs/app/lib/python3.11/site-packages/broker_rest_client/rabbitmq_rest_client.py", line 238, in get_user
    result = self.perform_request('GET', url, response_class=RabbitMQUser)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/app/lib/python3.11/site-packages/rest_client/requestor.py", line 70, in perform_request
    processed_response = self._process_response(response, response_class, many)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/app/lib/python3.11/site-packages/rest_client/requestor.py", line 100, in _process_response
    response_data = response_class.from_json(response_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/app/lib/python3.11/site-packages/broker_rest_client/models.py", line 68, in from_json
    tags=user_dict['tags'].split(',') if user_dict['tags'] else []
         ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'split'
